# Generated by Django 5.1.6 on 2025-02-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=50)),
                ('connected', models.BooleanField(default=False)),
                ('direction', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend')], max_length=20)),
                ('interviewed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
