# Generated by Django 5.1.6 on 2025-02-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interviewed',
        ),
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(choices=[('web', 'Web Development'), ('data', 'Data Science'), ('devops', 'DevOps'), ('ml', 'Machine Learning'), ('cloud', 'Cloud Computing'), ('mobile', 'Mobile Development'), ('network', 'Network Engineering')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
