# Generated by Django 5.1.6 on 2025-02-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_interviewed_alter_user_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend')], max_length=20),
        ),
    ]
