# Generated by Django 5.1.6 on 2025-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interview_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
