# Generated by Django 5.1.6 on 2025-02-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_interview_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend')], max_length=20),
        ),
    ]
