# Generated by Django 5.1.6 on 2025-02-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interview_time',
            new_name='interview_date',
        ),
    ]
