# Generated by Django 5.1.6 on 2025-02-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_interview_time_user_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='direction',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
