# Generated by Django 5.1.6 on 2025-02-10 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_trainer_direction_alter_trainer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.trainer'),
        ),
    ]
